server:
  servlet:
    context-path: /book-service
  port: '8080'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/scotiabank
    password: Nata8793*
  jpa:
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: update
  security:
    user:
      name: root
      password: scotiabank
      roles: ADMIN
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/