server:
  servlet:
    context-path: /book-service
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/scotiabank
    password: Nata8793*
  jpa:
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:scotiabank@localhost:8099/eureka/