server:
  port: 8080
spring:
  cloud:
    config:
      discovery:
        enabled: true    
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://root:scotiabank@localhost:8099/eureka/
zuul:
  routes:
    book-service:
      path: /book-service/**
    eureka-service:
      path: /eureka-service/**